language: node_js
node_js:
- '0.11'
- '0.10'
notifications:
  email:
    recipients:
    - neraliu@yahoo-inc.com
  on_success: change
  on_failure: always
after_success:
- test $(cat $TRAVIS_BUILD_DIR/package.json | grep version | awk '{print $2}' | sed
  's/"//g' | sed 's/,//g') = $TRAVIS_TAG && export VALID_VERSION=true
deploy:
  provider: npm
  email: neraliu@yahoo-inc.com
  api_key:
    secure: zfmnqdz4MU4Rw+CiSHBqmRXldJAe5UJw3tyTk91Wbzpa74Mgjn+zTFzmkI5rcdhu5553fuSrERXUTDaXQRj8ZcG+L1HJ0YbJYptha7zXfOLJjRLthRk4EF0U9O2AjlVAEfLrMVGtf6ORxzFZUrjYIfzlkKXHTc+5cxJD4eRiT6U=
  on:
    condition: $VALID_VERSION = true
    tags: true
    branch: master
